#!/usr/bin/env ruby

if File.directory?("lib")
  $: << "lib"
end

require "rubygems"
require "vendor/mysql"
require "mydiff"

config = {
  :host => "localhost",
  :user => "root",
  :password => nil,
  :prefix => "mydiff"
}

md = MyDiff.new(config)
md.prepare!

popt = config[:password].nil? ? "" : "-p#{config[:password]}"
system "mysql -h #{config[:host]} -u #{config[:user]} #{popt} #{md.newdb} < new.sql"
system "mysql -h #{config[:host]} -u #{config[:user]} #{popt} #{md.olddb} < old.sql"

puts "New tables"
puts md.new_tables.join("\n")

puts "\n"
puts "Dropped tables"
puts md.dropped_tables.join("\n")

puts "\n"
puts "Changed tables"
# puts md.changed_tables.join("\n")
md.changed_tables.each do |table|
  puts "#{table}\n\n"
  puts "New rows"
  md.new_rows(table).each do |row|
    puts row.values.join("||")
  end
  puts "Deleted rows"
  md.deleted_rows(table).each do |row|
    puts row.values.join("||")
  end
  puts "Changed rows"
  md.changed_rows(table).each do |row|
    puts row.values.join("||")
  end
end
